import type { ThemeConfig } from '../types'

export const ayutthayaThemeConfig: ThemeConfig = {
  id: 'ayutthaya',
  name: 'กรุงศรีอยุธยา',
  vehicleColors: [
    '#b5452b',
    '#1f6f8b',
    '#d4a017',
    '#6a3d9a',
    '#2e7d4f',
    '#c2185b',
    '#e07b24',
    '#3949ab',
    '#8d6e3f',
    '#00897b',
  ],
  // Only `sunset` is the default and the one the app currently shows (no time-of-day selector,
  // by spec); the others are config only, proving a new mood needs no scene rewrite.
  defaultTimeOfDay: 'sunset',
  lighting: {
    morning: {
      skyTop: '#a9c6e0',
      skyHorizon: '#ffd9a0',
      sunColor: '#fff0c2',
      sunIntensity: 2.0,
      sunDirection: [-30, 25, -60],
      hemisphereSky: '#dceeff',
      hemisphereGround: '#7d8f6a',
      hemisphereIntensity: 1.3,
      ambientIntensity: 0.4,
      fogColor: '#d7e6e8',
      surfacePrimary: '#6fb0a3',
      surfaceShadow: '#3f4d2e',
      surroundings: '#7fae5a',
    },
    day: {
      skyTop: '#3f8fd1',
      skyHorizon: '#bfe3f7',
      sunColor: '#fffdf0',
      sunIntensity: 3.2,
      sunDirection: [-10, 80, -20],
      hemisphereSky: '#cdeeff',
      hemisphereGround: '#7a8f5a',
      hemisphereIntensity: 1.6,
      ambientIntensity: 0.3,
      fogColor: '#cfe9ee',
      surfacePrimary: '#3fa89a',
      surfaceShadow: '#39492b',
      surroundings: '#8ec25a',
    },
    sunset: {
      skyTop: '#3d5a8a',
      skyHorizon: '#f7b267',
      sunColor: '#ffc27a',
      sunIntensity: 2.6,
      sunDirection: [-40, 45, -50],
      hemisphereSky: '#ffe2b8',
      hemisphereGround: '#6b5a3a',
      hemisphereIntensity: 1.5,
      ambientIntensity: 0.35,
      fogColor: '#f0b27a',
      surfacePrimary: '#5a9e8c',
      surfaceShadow: '#4a4a30',
      surroundings: '#9aa85a',
    },
    night: {
      skyTop: '#0b1533',
      skyHorizon: '#1c2c52',
      sunColor: '#b9c9ff',
      sunIntensity: 0.7,
      sunDirection: [30, 60, 40],
      hemisphereSky: '#26355c',
      hemisphereGround: '#141d2e',
      hemisphereIntensity: 0.6,
      ambientIntensity: 0.22,
      fogColor: '#101a33',
      surfacePrimary: '#1f3a4a',
      surfaceShadow: '#0d1710',
      surroundings: '#1c2818',
    },
  },
}
